name: 'Create UCD component version'
description: 'Create a new version for a UCD component'
inputs:
  component:
    description: 'Component Name/ID'
    required: true
  versionname:
    description: 'Component Version Name'
    required: true
  description:
    description: 'Component version description'
    required: false
  hostname:
    description: 'UCD hostname'
    required: true
  port:
    description: 'port'
    required: true
    default: '8443'
  username:
    description: 'username'
    required: true
  password:
    description: 'password'
    required: true
    secret: true
  authToken:
    description: 'UCD auth token'
    required: false
    secret: true
  disableSSLVerification:
    description: 'skip SSL certificate validation when making HTTPS requests and this is discouraged'
    required: true
    type: boolean
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'
